[phases.setup]
nixPkgs = ['python3', 'gcc', 'pkg-config', 'libffi', 'openssl']

[phases.install]
cmds = [
    'pip install --upgrade pip setuptools wheel',
    'pip install -r requirements.txt'
]

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port $PORT'
