[phases.setup]
nixPkgs = ['python3', 'python3Packages.pip', 'gcc', 'pkg-config', 'libffi', 'openssl']

[phases.install]
cmds = [
    'python3 -m pip install --upgrade pip setuptools wheel',
    'python3 -m pip install -r requirements.txt'
]

[start]
cmd = 'python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT'
